version: "3.9"
services:
  rabbit:
    image: "rabbitmq:3"
    ports:
      - "5672:5672"
  ms-dispatcher-weather:
    build:
      context: WeatherDispatcher
      dockerfile: Dockerfile
    depends_on:
      - rabbit

  ms-weather-request:
    build:
      context: MsweatherRequest
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - rabbit